default_language_version:
  python: python3.9

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: monthly
  skip: [mypy, shellcheck, shfmt]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - dataclasses-json
          - hydra-core
          - rhoknp==1.7.0
          - cohesion-tools==0.7.3
          - numpy
          - torch
          - torchmetrics
          - tokenizers==0.19.1
          - transformers==4.43.4
          - lightning==2.4.0
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        files: ^scripts/
        types: [ shell ]
      - id: shfmt
        files: ^scripts/
        types: [ shell ]
        args: [ -i 2 -sr ]
