defaults:
  - base.yaml

relation_head:
  _target_: mmrr.modules.model.components.BaseHeads
  hidden_dropout_prob: ${model.hidden_dropout_prob}
binary_head:
  _target_: mmrr.modules.model.components.TokenBinaryClassificationHead
  num_tasks: ${model.num_tasks}
  hidden_dropout_prob: ${model.hidden_dropout_prob}
