defaults:
  - base.yaml

relation_head:
  _target_: mmrr.modules.model.components.KWJAHeads
  hidden_dropout_prob: ${model.hidden_dropout_prob}
  rank: 2
binary_head:
  _target_: mmrr.modules.model.components.LoRARelationWiseTokenBinaryClassificationHead
  num_tasks: ${model.num_tasks}
  hidden_dropout_prob: ${model.hidden_dropout_prob}
  rank: 2
