_target_: modules.model.mmref.baseline.BaselineModel
model_name_or_path: ${model_name_or_path}
exophora_referents: ${exophora_referents}
hidden_dropout_prob: 0.05
num_tasks: ${len:${tasks}}
vis_emb_size: ${vis_emb_size}
