_target_: pytorch_lightning.loggers.WandbLogger
name: ${config_name}_${name}
save_dir: ${save_dir}
project: cl_cohesion
log_model: false
group: ${config_name}_${name}
tags:
  - ${config_name}
settings:
  _target_: wandb.Settings
  start_method: fork
