_target_: pytorch_lightning.loggers.WandbLogger
name: ${name}_${run_id}
save_dir: ${save_dir}
project: mmrr_mmref
log_model: false
group: ${config_name}_${name}
tags:
  - ${config_name}
settings:
  _target_: wandb.Settings
  start_method: fork
