defaults:
  - _self_

# Path to checkpoint.
checkpoint: /somewhere/model.ckpt

# Path to dir where documents and annotatios.
input_dir: null
# File dir/name of the object features (xxx.h5 and xxx_mapper.h5)
object_file_root: null
object_file_name: null

# Directory where analyzed knp files are exported.
export_dir: null

# environment-dependent settings
devices: ${oc.env:DEVICES,1}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,4}
num_workers: ${oc.env:NUM_WORKERS,4}
compile: ${oc.env:COMPILE,false}
