defaults:
  - _self_

# Path to checkpoint.
checkpoint: /somewhere/model.ckpt

# Path to dir where documents and annotatios.
input_dir: null
# File name of the object features (xxx.h5)
object_file_name: null

# Directory where analyzed knp files are exported.
export_dir: null
# Threshold for analysis target prediction probability. If the probability is lower than this value, the base phrase is
# not analyzed.
analysis_target_threshold: 0.3

# environment-dependent settings
devices: ${oc.env:DEVICES,1}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,4}
num_workers: ${oc.env:NUM_WORKERS,4}
compile: ${oc.env:COMPILE,false}
