defaults:
  - base.yaml
  - callbacks: [early_stopping_cohesion, model_checkpoint, model_summary, progress_bar]
  - datamodule: cohesion_jcre3
  - logger: null
  - model: cohesion_baseline
  - module: cohesion
  - optimizer: adamw
  - scheduler: cosine_schedule_with_warmup
  - trainer: debug
  - _self_

dataset_path: ./data
max_seq_length: 64
model_name_or_path: "ku-nlp/deberta-v2-tiny-japanese"
frw: false
flip_reader_writer: ${frw}
checkpoint: "" # path to trained checkpoint
document_split_stride: -1
analysis_target_threshold: 0.3

# experimental settings
metric_learning_loss: {"contrastive_alignment_loss": 1.0}
cases: ["ガ", "ヲ", "ニ"]
bar_rels: ["ノ"]
exophora_referents:
  - 著者
  - 読者
  - 不特定:人
  - 不特定:物
tasks: ["pas", "bridging", "coreference"]
special_tokens:
  ["[著者]", "[読者]", "[不特定:人]", "[不特定:物]", "[NULL]", "[NA]"]

# hyper-parameters to be tuned
effective_batch_size: 2
max_epochs: 2
lr: 0.00005
warmup_steps: null
warmup_ratio: 0.1

# environment-dependent settings
devices: ${oc.env:DEVICES,1}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,4}
num_workers: ${oc.env:NUM_WORKERS,0}
compile: ${oc.env:COMPILE,false}
