defaults:
  - base.yaml
  - callbacks:
      [early_stopping_cohesion, model_checkpoint, model_summary, lr_monitor]
  - datamodule: cohesion_all
  - logger: cohesion
  - model: cohesion_single
  - module: cohesion
  - optimizer: adamw
  - scheduler: cosine_schedule_with_warmup
  - trainer: default
  - _self_

dataset_path: ./data
max_seq_length: 256
model_name_or_path: "ku-nlp/deberta-v2-base-japanese"
frw: false
flip_reader_writer: ${frw}
target_checkpoint: "" # path to trained checkpoint
source_checkpoint: "" # specify trained mmref model
document_split_stride: 2
analysis_target_threshold: 0.3

# experimental settings
cases: ["ガ", "ヲ", "ニ", "デ"]
bar_rels: ["ノ"]
exophora_referents:
  - 著者
  - 読者
  - 不特定:人
  - 不特定:物
tasks: ["pas", "bridging", "coreference"]
special_tokens:
  ["[著者]", "[読者]", "[不特定:人]", "[不特定:物]", "[NULL]", "[NA]"]

# hyper-parameters to be tuned
effective_batch_size: 16
max_epochs: 16
lr: 0.00005
warmup_steps: 1000
warmup_ratio: null

# environment-dependent settings
devices: ${oc.env:DEVICES,4}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,4}
num_workers: ${oc.env:NUM_WORKERS,4}
compile: ${oc.env:COMPILE,false}
