defaults:
        - train:
                  - cohesion/jcre3.yaml
        - valid:
                  - cohesion/jcre3.yaml
        - test:
                  - cohesion/jcre3.yaml
#   - predict:
#       - custom.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
