defaults:
  - train:
    - fuman_cohesion.yaml
    - jcre3_cohesion.yaml
    - kwdlc_cohesion.yaml
    - wac_cohesion.yaml
  - valid:
    - fuman_cohesion.yaml
    - jcre3_cohesion.yaml
    - kwdlc_cohesion.yaml
    - wac_cohesion.yaml
  - test:
    - fuman_cohesion.yaml
    - jcre3_cohesion.yaml
    - kwdlc_cohesion.yaml
    - wac_cohesion.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
